#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99
STOP=99

[ ! -e /etc/config/mcuiocfg ] && exit 0

source /etc/config/mcuiocfg

start() {
	for i in $SHIELDS; do
		echo $i > /sys/devices/mcuio/shield_register
	done
}

stop() {
	for i in $SHIELDS; do
		echo $i > /sys/devices/mcuio/shield_unregister
	done
}
