#!/bin/sh /etc/rc.common
#Init script for udevd

START=30

start() {
    #----------- create run dir ---------------------
    [ ! -d /run/udev ] && mkdir -p /run/udev
    #----------- START the UDEV daemon --------------
    /sbin/udevd --daemon &
    }

stop() {
    killall udevd
}
